<?php


$nuevaTemporada = [
    1 => ['id' => 1, 'nombre' => 'SUDADERA CREMALLERA HEAVY WEIGHT CAPUCHA', 'precio' => 49.95, 'img' => 'img/nuevaTemporada/new1.jpg'],
    2 => ['id' => 2, 'nombre' => 'SUDADERA CREMALLERA HEAVY WEIGHT CAPUCHA', 'precio' => 49.95, 'img' => 'img/nuevaTemporada/new2.jpg'],
    3 => ['id' => 3, 'nombre' => 'PANTALÓN TÉCNICO PARACHUTE', 'precio' => 49.95, 'img' => 'img/nuevaTemporada/new3.jpg'],
    4 => ['id' => 4, 'nombre' => 'SUDADERA CREMALLERA HEAVY WEIGHT CAPUCHA', 'precio' => 49.95, 'img' => 'img/nuevaTemporada/new4.jpg'],
    5 => ['id' => 5, 'nombre' => 'PANTALÓN JOGGER HEAVY WEIGHT', 'precio' => 39.95 , 'img' => 'img/nuevaTemporada/new5.jpg'],
    6 => ['id' => 6, 'nombre' => 'PANTALÓN CARPINTERO LAVADO SALPICADURAS', 'precio' => 49.95, 'img' => 'img/nuevaTemporada/new6.jpg'],
    7 => ['id' => 7, 'nombre' => 'CAMISETA EXTRA HEAVY WEIGHT', 'precio' => 25.85, 'img' => 'img/nuevaTemporada/new7.jpg'],
    8 => ['id' => 8, 'nombre' => 'SUDADERA LAVADA TEXTOS', 'precio' => 25.95, 'img' => 'img/nuevaTemporada/new8.jpg'],
    9 => ['id' => 9, 'nombre' => 'PANTALÓN JOGGER TÉCNICO CREMALLERAS', 'precio' => 29.95, 'img' => 'img/nuevaTemporada/new9.jpg'],
    10 => ['id' => 10, 'nombre' => 'SUDADERA LAVADA RAYAS', 'precio' => 29.95, 'img' => 'img/nuevaTemporada/new10.jpg'],
    11 => ['id' => 11, 'nombre' => 'PANTALÓN JOGGER', 'precio' => 29.95, 'img' => 'img/nuevaTemporada/new11.jpg'],
    12 => ['id' => 12, 'nombre' => 'CAZADORA BIKER PIEL', 'precio' => 50.00, 'img' => 'img/nuevaTemporada/new12.jpg'],
    13 => ['id' => 13, 'nombre' => 'JEANS FLARED FIT', 'precio' => 30.00, 'img' => 'img/nuevaTemporada/new13.jpg'],
    14 => ['id' => 14, 'nombre' => 'PANTALÓN CARGO RELAXED FIT', 'precio' => 35.95, 'img' => 'img/nuevaTemporada/new14.jpg'],
    15 => ['id' => 15, 'nombre' => 'CAMISETA TEXTO ENGOMADO LIMITED EDITION', 'precio' => 19.95, 'img' => 'img/nuevaTemporada/new15.jpg'],
    16 => ['id' => 16, 'nombre' => 'ABRIGO CON LANA', 'precio' => 39.99, 'img' => 'img/nuevaTemporada/new16.jpg'],
    17 => ['id' => 17, 'nombre' => 'CAMISA ELÁSTICA RAYAS', 'precio' => 35.95, 'img' => 'img/nuevaTemporada/new17.jpg'],
    18 => ['id' => 18, 'nombre' => 'SUDADERA BÁSICA CUELLO CREMALLERA', 'precio' => 27.95, 'img' => 'img/nuevaTemporada/new18.jpg'],
    19 => ['id' => 19, 'nombre' => 'JEANS STRAIGHT FIT', 'precio' => 29.95, 'img' => 'img/nuevaTemporada/new19.jpg'],
    20 => ['id' => 20, 'nombre' => 'SUDADERA BORDADOS CUELLO CREMALLERA', 'precio' => 35.95, 'img' => 'img/nuevaTemporada/new20.jpg'],
];

$oferta = [
    1 => ['id' => 1, 'nombre' => 'ABRIGO CON LANA', 'precio' => 39.99, 'img' => 'img/oferta/of1.jpg'],
    2 => ['id' => 2, 'nombre' => 'SUDADERA BÁSICA CUELLO CREMALLERA', 'precio' => 15.99, 'img' => 'img/oferta/of2.jpg'],
    3 => ['id' => 3, 'nombre' => 'SUDADERA BÁSICA CUELLO CREMALLERA', 'precio' => 15.99, 'img' => 'img/oferta/of3.jpg'],
    4 => ['id' => 4, 'nombre' => 'BOTA CORDONES PIEL', 'precio' => 29.99, 'img' => 'img/oferta/of4.jpg'],
    5 => ['id' => 5, 'nombre' => 'MOCHILA TEXTURA', 'precio' => 29.99, 'img' => 'img/oferta/of5.jpg'],
    6 => ['id' => 6, 'nombre' => 'CAZADORA ACOLCHADA LIGERA', 'precio' => 19.99, 'img' => 'img/oferta/of6.jpg'],
    7 => ['id' => 7, 'nombre' => 'JERSEY BÁSICO CUELLO PERKINS', 'precio' => 17.99, 'img' => 'img/oferta/of7.jpg'],
    8 => ['id' => 8, 'nombre' => 'BANDOLERA RÍGIDA', 'precio' => 15.99, 'img' => 'img/oferta/of8.jpg'],
    9 => ['id' => 9, 'nombre' => 'RIÑONERA ENGOMADA', 'precio' => 9.99, 'img' => 'img/oferta/of9.jpg'],
    10 => ['id' => 10, 'nombre' => 'SUDADERA BÁSICA CREW NECK', 'precio' => 12.99, 'img' => 'img/oferta/of10.jpg'],
    11 => ['id' => 11, 'nombre' => 'ABRIGO CON LANA', 'precio' => 39.99, 'img' => 'img/oferta/of11.jpg'],
    12 => ['id' => 12, 'nombre' => 'JEANS SLIM FIT', 'precio' => 25.95, 'img' => 'img/oferta/of12.jpg'],
    13 => ['id' => 13, 'nombre' => 'CAMISA ESTRUCTURA CUADROS', 'precio' => 35.95, 'img' => 'img/oferta/of13.jpg'],
    14 => ['id' => 14, 'nombre' => 'PANTALÓN CHINO SKINNY FIT', 'precio' => 25.95, 'img' => 'img/oferta/of14.jpg'],
    15 => ['id' => 15, 'nombre' => 'JERSEY CREMALLERA CUELLO', 'precio' => 35.95, 'img' => 'img/oferta/of15.jpg'],
    16 => ['id' => 16, 'nombre' => 'JEANS SLIM CROPPED FIT', 'precio' => 25.95, 'img' => 'img/oferta/of16.jpg'],
    17 => ['id' => 17, 'nombre' => 'CAMISETA BÁSICA SLIM FIT', 'precio' => 9.95, 'img' => 'img/oferta/of17.jpg'],
    18 => ['id' => 18, 'nombre' => 'CAZADORA BOMBER REVERSIBLE', 'precio' => 69.95, 'img' => 'img/oferta/of18.jpg'],
    19 => ['id' => 19, 'nombre' => 'JERSEY CREMALLERA CUELLO', 'precio' => 35.95, 'img' => 'img/oferta/of19.jpg'],
    20 => ['id' => 20, 'nombre' => 'CAZADORA BIKER EFECTO PIEL', 'precio' => 55.95, 'img' => 'img/oferta/of20.jpg'],

];

$outlet = [
    1 => ['id' => 1, 'nombre' => 'POLO PUNTO JACQUARD', 'precio' => 35.95, 'img' => 'img/outlet/ou1.jpg'],
    2 => ['id' => 2, 'nombre' => 'POLO ESTRUCTURA CALADOS', 'precio' => 29.95, 'img' => 'img/outlet/ou2.jpg'],
    3 => ['id' => 3, 'nombre' => 'POLO PUNTO JACQUARD ROMBOS', 'precio' => 29.95, 'img' => 'img/outlet/ou3.jpg'],
    4 => ['id' => 4, 'nombre' => 'POLO ESTRUCTURA CANALÉ', 'precio' => 25.95, 'img' => 'img/outlet/ou4.jpg'],
    5 => ['id' => 5, 'nombre' => 'BLAZER TRAJE CONFORT', 'precio' => 69.95, 'img' => 'img/outlet/ou5.jpg'],
    6 => ['id' => 6, 'nombre' => 'BLAZER TRAJE SLIM FIT', 'precio' => 69.95, 'img' => 'img/outlet/ou6.jpg'],
    7 => ['id' => 7, 'nombre' => 'BLAZER TRAJE CONFORT', 'precio' => 69.95, 'img' => 'img/outlet/ou7.jpg'],
    8 => ['id' => 8, 'nombre' => 'CAZADORA DENIM LAVADO', 'precio' => 79.95, 'img' => 'img/outlet/ou8.jpg'],
    9 => ['id' => 9, 'nombre' => 'CAZADORA LAVADO SALPICADURAS', 'precio' => 79.95, 'img' => 'img/outlet/ou9.jpg'],
    10 => ['id' => 10, 'nombre' => 'CAZADORA DENIM CREMALLERA', 'precio' => 69.95, 'img' => 'img/outlet/ou10.jpg'],
    11 => ['id' => 11, 'nombre' => 'CAZADORA PIEL LAVADA', 'precio' => 249.00, 'img' => 'img/outlet/ou11.jpg'],
    12 => ['id' => 12, 'nombre' => 'JEANS SLIM FIT', 'precio' => 25.95, 'img' => 'img/outlet/ou12.jpg'],
    13 => ['id' => 13, 'nombre' => 'PARKA ACOLCHADA CUELLO DESMONTABLE', 'precio' => 89.95, 'img' => 'img/outlet/ou13.jpg'],
    14 => ['id' => 14, 'nombre' => 'SUDADERA CAPUCHA CORAZÓN LIMITED EDITION', 'precio' => 39.95, 'img' => 'img/outlet/ou14.jpg'],
    15 => ['id' => 15, 'nombre' => 'JEANS FLARE FIT', 'precio' => 39.95, 'img' => 'img/outlet/ou15.jpg'],
    16 => ['id' => 16, 'nombre' => 'CAMISA CUADROS', 'precio' => 35.95, 'img' => 'img/outlet/ou16.jpg'],
    17 => ['id' => 17, 'nombre' => 'MALETA DE VIAJE', 'precio' => 119.00, 'img' => 'img/outlet/ou17.jpg'],
    18 => ['id' => 18, 'nombre' => 'BLAZER TRAJE CONFORT', 'precio' => 69.95, 'img' => 'img/outlet/ou18.jpg'],
    19 => ['id' => 19, 'nombre' => 'SUDADERA BÁSICA CAPUCHA', 'precio' => 27.95, 'img' => 'img/outlet/ou19.jpg'],
    20 => ['id' => 20, 'nombre' => 'PANTALÓN CHINO SKINNY FIT', 'precio' => 25.95, 'img' => 'img/outlet/ou20.jpg'],
];

$productosNormales = [
    1 => ['id' => 1, 'nombre' => 'PULSERA ESLABONES METÁLICOS', 'precio' => 17.95, 'img' => 'img/productosNormales/pn1.jpg'],
    2 => ['id' => 2, 'nombre' => 'CADENA ESLABONES METÁLICOS', 'precio' => 19.95, 'img' => 'img/productosNormales/pn2.jpg'],
    3 => ['id' => 3, 'nombre' => 'ANILLO COMBINADO PIEDRA', 'precio' => 19.95, 'img' => 'img/productosNormales/pn3.jpg'],
    4 => ['id' => 4, 'nombre' => 'ANILLO GRABADO COMBINADO PIEDRA', 'precio' => 19.95, 'img' => 'img/productosNormales/pn4.jpg'],
    5 => ['id' => 5, 'nombre' => 'BÓXER BÁSICO PACK 3', 'precio' => 19.95, 'img' => 'img/productosNormales/pn5.jpg'],
    6 => ['id' => 6, 'nombre' => 'GAFAS DE SOL RECTANGULARES', 'precio' => 49.95, 'img' => 'img/productosNormales/pn6.jpg'],
    7 => ['id' => 7, 'nombre' => 'GORRO BÁSICO PUNTO', 'precio' => 12.95, 'img' => 'img/productosNormales/pn7.jpg'],
    8 => ['id' => 8, 'nombre' => 'CINTURÓN PIEL VESTIR', 'precio' => 25.95, 'img' => 'img/productosNormales/pn8.jpg'],
    9 => ['id' => 9, 'nombre' => 'BÓXER POPELÍN RAYAS LIMITED EDITION', 'precio' => 19.95,  'img' => 'img/productosNormales/pn9.jpg'],
    10 => ['id' => 10, 'nombre' => 'BÓXER POPELÍN RAYAS LIMITED EDITION', 'precio' => 19.95, 'img' => 'img/productosNormales/pn10.jpg'],
    11 => ['id' => 11, 'nombre' => 'GORRA VISOR PLANO BORDADO LIMITED EDITION', 'precio' => 15.95, 'img' => 'img/productosNormales/pn11.jpg'],
    12 => ['id' => 12, 'nombre' => 'JERSEY LAVADO CANALÉ', 'precio' => 35.95, 'img' => 'img/productosNormales/pn12.jpg'],
    13 => ['id' => 13, 'nombre' => 'PANTALÓN CHINO SKINNY FIT', 'precio' => 25.95, 'img' => 'img/productosNormales/pn13.jpg'],
    14 => ['id' => 14, 'nombre' => 'CAMISA CUADROS', 'precio' => 35.95, 'img' => 'img/productosNormales/pn14.jpg'],
    15 => ['id' => 15, 'nombre' => 'CAMISETA ESTAMPADO TOSTADA LIMITED EDITION', 'precio' => 19.95, 'img' => 'img/productosNormales/pn15.jpg'],
    16 => ['id' => 16, 'nombre' => 'CAMISETA BÁSICA SLIM FIT', 'precio' => 9.95, 'img' => 'img/productosNormales/pn16.jpg'],
    17 => ['id' => 17, 'nombre' => 'CAMISA 100% LINO', 'precio' => 35.95, 'img' => 'img/productosNormales/pn17.jpg'],
    18 => ['id' => 18, 'nombre' => 'PANTALÓN SLIM FIT CONFORT', 'precio' => 29.95, 'img' => 'img/productosNormales/pn18.jpg'],
    19 => ['id' => 19, 'nombre' => 'PANTALÓN SLIM FIT CONFORT', 'precio' => 29.95, 'img' => 'img/productosNormales/pn19.jpg'],
    20 => ['id' => 20, 'nombre' => 'ABRIGO OVERSIZE FIT', 'precio' => 69.95, 'img' => 'img/productosNormales/pn20.jpg'],

];

$rebajas = [
    1 => ['id' => 1, 'nombre' => 'SOBRECAMISA CUADROS TEXTURA', 'precio' => 9.99,  'img' => 'img/rebajas/r1.jpg'],
    2 => ['id' => 2, 'nombre' => 'PARKA ACOLCHADA WATER REPELLENT', 'precio' => 39.99, 'img' => 'img/rebajas/r2.jpg'],
    3 => ['id' => 3, 'nombre' => 'CAZADORA EFECTO PIEL DOBLE FAZ', 'precio' => 39.99, 'img' => 'img/rebajas/r3.jpg'],
    4 => ['id' => 4, 'nombre' => 'CHAQUETA DENIM BOLSILLOS', 'precio' => 9.99, 'img' => 'img/rebajas/r4.jpg'],
    5 => ['id' => 5, 'nombre' => 'CAZADORA ACOLCHADA CAPUCHA', 'precio' => 39.99, 'img' => 'img/rebajas/r5.jpg'],
    6 => ['id' => 6, 'nombre' => 'SOBRECAMISA DENIM CAPUCHA COMBINADA', 'precio' => 9.99, 'img' => 'img/rebajas/r6.jpg'],
    7 => ['id' => 7, 'nombre' => 'SOBRECAMISA ESTRUCTURA BOLSILLOS', 'precio' => 9.99, 'img' => 'img/rebajas/r7.jpg'],
    8 => ['id' => 8, 'nombre' => 'CAZADORA ACOLCHADA BOXY FIT', 'precio' => 29.99, 'img' => 'img/rebajas/r8.jpg'],
    9 => ['id' => 9, 'nombre' => 'CAZADORA ACOLCHADA EFECTO PIEL', 'precio' => 29.99, 'img' => 'img/rebajas/r9.jpg'],
    10 => ['id' => 10, 'nombre' => 'CAZADORA ACOLCHADA CAPUCHA', 'precio' => 39.99, 'img' => 'img/rebajas/r10.jpg'],
    11 => ['id' => 11, 'nombre' => 'CAZADORA ESTRUCTURA', 'precio' => 9.99, 'img' => 'img/rebajas/r11.jpg'],
    12 => ['id' => 12, 'nombre' => 'POLO PUNTO PERLADO', 'precio' => 39.95, 'img' => 'img/rebajas/r12.jpg'],
    13 => ['id' => 13, 'nombre' => 'SUDADERA LAVADA CREMALLERA TEXTOS', 'precio' => 39.95, 'img' => 'img/rebajas/r13.jpg'],
    14 => ['id' => 14, 'nombre' => 'SUDADERA CUELLO CREMALLERA', 'precio' => 39.95, 'img' => 'img/rebajas/r14.jpg'],
    15 => ['id' => 15, 'nombre' => 'SUDADERA BÁSICA CUELLO CREMALLERA', 'precio' => 27.95, 'img' => 'img/rebajas/r15.jpg'],
    16 => ['id' => 16, 'nombre' => 'PANTALÓN CHINO SKINNY FIT', 'precio' => 25.95, 'img' => 'img/rebajas/r16.jpg'],
    17 => ['id' => 17, 'nombre' => 'PARKA ENCERADA CUELLO COMBINADO', 'precio' => 89.95, 'img' => 'img/rebajas/r17.jpg'],
    18 => ['id' => 18, 'nombre' => 'CAMISA ESTRUCTURA RAYAS', 'precio' => 35.95, 'img' => 'img/rebajas/r18.jpg'],
    19 => ['id' => 19, 'nombre' => 'JERSEY PERKINS CREMALLERA', 'precio' => 35.95, 'img' => 'img/rebajas/r19.jpg'],
    20 => ['id' => 20, 'nombre' => 'MOCASÍN CASTELLANO 1920', 'precio' => 175.00, 'img' => 'img/rebajas/r20.jpg'],
];

?>